Base and Weather Ingress
alan-turing-institute/DTBase pull request #174
Opened 2023-12-19 17:07 UTC by EdwinB12

Includes: 

- BaseIngress for shared utilities. Class to be inherited by specific data ingress options. 
- Readme describing what the BaseIngress is and how to use it to write custom DataIngress Classes. 
- OpenWeatherDataIngress Class for ingressing weather data from OpenWeatherMap API. 
- Basic tests for handling dt_from and dt_to. These are the variables determining what time range to pul data from. 

TODO before merging : 

- Tests for BaseClass methods. Will require a simple mocking of the `get_data` method.  
- Tests for OpenWeatherDataIngress methods 

TODO but perhaps different PR: 

- Azure Functions Utility. Hopefully can be included into BaseIngress

2024-01-02 12:24 UTC, mhauru commented on dtbase/ingress/README.md
> +We then write a custom class that inherits from BaseIngress. There are a number of _* methods that are used to handle different combinations of start and end dates given by the user. A lot of this co
```suggestion
We then write a custom class that inherits from BaseIngress. There are a number of _* methods that are used to handle different combinations of start and end dates given by the user. A lot of this complexity comes from there being two different APIs.
```

2024-01-02 12:26 UTC, mhauru commented
>TODO but perhaps different PR:
    Azure Functions Utility. Hopefully can be included into BaseIngress

Yeah, agreed, this can be a separate PR.

2024-01-08 09:38 UTC, EdwinB12 commented
@mhauru - I'm reading in some hardcoded responses for mocking purposes (such as MOCKED_CONST_OPENWEATHERMAP_HISTORICAL_URL_RESPONSE). They are quite large dictionaries. Have you got any strong opinions on where I should store these dictionaries: 

- In test_ingress_weather.py 
- In conftest.py (Have them as fixtures). 
- In a seperate resources file (this is what I've currently implemented).

2024-01-08 09:57 UTC, mhauru commented
The separate resource files sound good to me.

2024-01-10 12:02 UTC, mhauru requested changes
Looks great. I had a number of small suggestions, I put them in a PR that is asking to be merged to your branch: https://github.com/alan-turing-institute/DTBase/pull/178

2024-01-10 12:05 UTC, mhauru commented
One thing I was thinking of was that maybe there should be a separate pair of OpenWeatherMap sensors (historical and forecast) for every lat/long. That the lat and the long would be in the unique identifier of the sensor. Maybe this is for a separate PR though. I'm in general not fully happy with how we currently use environment variables, there may be a bit of an overhaul to do there, but it might make sense to do once things are running on Azure, since envvars are often the best way to handle parameters there.

2024-01-10 12:20 UTC, mhauru approved these changes

2024-01-10 12:29 UTC, merged